import NavigationBar from "@/app/components/NavigationBar";
import FooterSection from "@/app/components/FooterSection";
import { ArrowLeft, Lock, Key, Shield, ArrowRight } from "lucide-react";
import { motion } from "motion/react";
import { Link } from "react-router";

export default function ChiffrementE2EPage() {
  return (
    <div className="min-h-screen bg-background">
      <NavigationBar />
      <section className="pt-32 pb-8 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><Link to="/help" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-terracotta transition-colors font-sans"><ArrowLeft className="w-4 h-4" />Retour au Centre d'Aide</Link></div></section>
      <section className="pb-12 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}><div className="inline-block px-4 py-2 bg-anthracite/10 border border-anthracite/20 rounded-full mb-6"><span className="text-sm text-anthracite font-sans font-medium">Confidentialité & Sécurité</span></div><h1 className="text-4xl lg:text-5xl font-serif text-anthracite mb-6">Comment fonctionne le chiffrement E2E ?</h1><p className="text-lg text-muted-foreground font-sans">Le chiffrement de bout en bout (E2E) garantit que personne, même pas M.O.N.A, ne peut lire vos conversations. Voici comment cela fonctionne de manière simple.</p></motion.div></div></section>
      <section className="py-12 bg-gradient-to-b from-white to-beige/10"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><h2 className="text-3xl font-serif text-anthracite mb-6">Le principe en 3 étapes</h2><div className="space-y-6"><div className="bg-white border border-beige/30 rounded-xl p-8"><div className="flex items-start gap-6"><div className="w-14 h-14 bg-terracotta/10 rounded-full flex items-center justify-center flex-shrink-0"><Lock className="w-7 h-7 text-terracotta" /></div><div><h3 className="text-2xl font-serif text-anthracite mb-3">1. Chiffrement sur votre appareil</h3><p className="text-base text-muted-foreground font-sans leading-relaxed">Lorsque vous envoyez un message ou démarrez une visio, vos données sont instantanément chiffrées directement sur votre téléphone ou ordinateur avec une clé unique. Personne d'autre que vous et votre thérapeute ne possède cette clé.</p></div></div></div><div className="bg-white border border-beige/30 rounded-xl p-8"><div className="flex items-start gap-6"><div className="w-14 h-14 bg-gold/10 rounded-full flex items-center justify-center flex-shrink-0"><Shield className="w-7 h-7 text-gold" /></div><div><h3 className="text-2xl font-serif text-anthracite mb-3">2. Transit sécurisé</h3><p className="text-base text-muted-foreground font-sans leading-relaxed">Les données chiffrées transitent par nos serveurs, mais nous ne pouvons pas les lire. Elles ressemblent à du charabia illisible pour quiconque les intercepterait. Même nos ingénieurs ne peuvent pas y accéder.</p></div></div></div><div className="bg-white border border-beige/30 rounded-xl p-8"><div className="flex items-start gap-6"><div className="w-14 h-14 bg-anthracite/10 rounded-full flex items-center justify-center flex-shrink-0"><Key className="w-7 h-7 text-anthracite" /></div><div><h3 className="text-2xl font-serif text-anthracite mb-3">3. Déchiffrement chez le destinataire</h3><p className="text-base text-muted-foreground font-sans leading-relaxed">Seul votre thérapeute, avec sa clé privée unique, peut déchiffrer et lire vos messages. Le message redevient lisible uniquement sur son appareil, jamais ailleurs.</p></div></div></div></div></motion.div></div></section>
      <section className="py-12 bg-gradient-to-br from-anthracite via-anthracite to-anthracite/90 text-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center"><h2 className="text-3xl font-serif mb-4">Pourquoi c'est important ?</h2><p className="text-lg text-white/80 font-sans leading-relaxed max-w-2xl mx-auto mb-8">Le chiffrement E2E vous offre la même confidentialité qu'une conversation dans un cabinet fermé à clé. C'est la norme gold standard utilisée par les messageries les plus sécurisées au monde comme Signal ou WhatsApp.</p><div className="grid md:grid-cols-3 gap-6"><div className="bg-white/5 backdrop-blur-sm border border-white/10 p-6 rounded-xl"><div className="text-4xl font-serif text-terracotta mb-2">0</div><p className="text-sm text-white/80 font-sans">Personnes peuvent lire vos échanges en dehors de vous et votre expert</p></div><div className="bg-white/5 backdrop-blur-sm border border-white/10 p-6 rounded-xl"><div className="text-4xl font-serif text-gold mb-2">256-bit</div><p className="text-sm text-white/80 font-sans">Niveau de chiffrement AES militaire utilisé</p></div><div className="bg-white/5 backdrop-blur-sm border border-white/10 p-6 rounded-xl"><div className="text-4xl font-serif text-beige mb-2">100%</div><p className="text-sm text-white/80 font-sans">Des conversations chiffrées automatiquement</p></div></div></motion.div></div></section>
      <section className="py-12 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><div className="bg-gradient-to-br from-terracotta/5 via-beige/10 to-gold/5 border border-beige/30 rounded-2xl p-8"><h3 className="text-2xl font-serif text-anthracite mb-4">Questions fréquentes</h3><div className="space-y-6"><div><h4 className="text-lg font-serif text-anthracite mb-2">M.O.N.A peut-il lire mes messages ?</h4><p className="text-base text-muted-foreground font-sans">Non, absolument pas. Le chiffrement E2E empêche quiconque, y compris M.O.N.A, de lire vos échanges.</p></div><div><h4 className="text-lg font-serif text-anthracite mb-2">Mes données sont-elles enregistrées quelque part ?</h4><p className="text-base text-muted-foreground font-sans">Vos données sont stockées de manière chiffrée. Seuls vous et votre thérapeute pouvez les déchiffrer avec vos clés privées respectives.</p></div><div><h4 className="text-lg font-serif text-anthracite mb-2">Que se passe-t-il si je perds mon mot de passe ?</h4><p className="text-base text-muted-foreground font-sans">Vous pouvez réinitialiser votre mot de passe, mais certaines données anciennes chiffrées avec l'ancienne clé pourraient ne plus être accessibles. C'est le prix de la sécurité maximale.</p></div></div></div></motion.div></div></section>
      <section className="py-20 bg-gradient-to-b from-white to-beige/10"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-serif text-anthracite mb-6">Articles associés</h2><div className="grid md:grid-cols-2 gap-4"><Link to="/help/donnees-securisees" className="p-6 bg-white hover:bg-beige/5 border border-beige/30 rounded-xl transition-all duration-200 group"><h3 className="text-lg font-serif text-anthracite group-hover:text-terracotta transition-colors mb-2">Mes données sont-elles sécurisées ?</h3><p className="text-sm text-muted-foreground font-sans">Toutes nos mesures de sécurité expliquées.</p></Link><Link to="/help/acces-informations" className="p-6 bg-white hover:bg-beige/5 border border-beige/30 rounded-xl transition-all duration-200 group"><h3 className="text-lg font-serif text-anthracite group-hover:text-terracotta transition-colors mb-2">Qui a accès à mes informations ?</h3><p className="text-sm text-muted-foreground font-sans">Découvrez qui peut voir vos données.</p></Link></div></div></section>
      <FooterSection />
    </div>
  );
}
