import NavigationBar from "@/app/components/NavigationBar";
import FooterSection from "@/app/components/FooterSection";
import { ArrowLeft, Wifi, WifiOff, CheckCircle, ArrowRight } from "lucide-react";
import { motion } from "motion/react";
import { Link } from "react-router";

export default function FonctionnementOfflinePage() {
  return (
    <div className="min-h-screen bg-background">
      <NavigationBar />
      <section className="pt-32 pb-8 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><Link to="/help" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-terracotta transition-colors font-sans"><ArrowLeft className="w-4 h-4" />Retour au Centre d'Aide</Link></div></section>
      <section className="pb-12 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}><div className="inline-block px-4 py-2 bg-beige/20 border border-beige/30 rounded-full mb-6"><span className="text-sm text-beige font-sans font-medium">Application Mobile</span></div><h1 className="text-4xl lg:text-5xl font-serif text-anthracite mb-6">L'app fonctionne-t-elle hors ligne ?</h1><p className="text-lg text-muted-foreground font-sans">Oui ! L'application M.O.N.A est conçue pour l'Afrique : elle fonctionne même avec une connexion limitée ou absente. Accédez à vos ressources essentielles où que vous soyez.</p></motion.div></div></section>
      <section className="py-12 bg-gradient-to-b from-white to-beige/10"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><div className="grid md:grid-cols-2 gap-8 mb-12"><div className="bg-white border border-beige/30 rounded-2xl p-8"><div className="flex items-center gap-4 mb-6"><Wifi className="w-8 h-8 text-terracotta" /><h2 className="text-2xl font-serif text-anthracite">Avec connexion</h2></div><ul className="space-y-3"><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-terracotta flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Téléconsultations vidéo HD</span></li><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-terracotta flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Messagerie sécurisée en temps réel</span></li><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-terracotta flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Synchronisation automatique du Passeport Santé</span></li><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-terracotta flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Accès à toute la bibliothèque de ressources</span></li><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-terracotta flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Réservation de rendez-vous</span></li></ul></div><div className="bg-gradient-to-br from-beige/20 via-beige/10 to-gold/5 border border-beige/30 rounded-2xl p-8"><div className="flex items-center gap-4 mb-6"><WifiOff className="w-8 h-8 text-gold" /><h2 className="text-2xl font-serif text-anthracite">Sans connexion</h2></div><ul className="space-y-3"><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Accès à votre Passeport Santé (FHIR)</span></li><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Lecture des articles et guides téléchargés</span></li><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Exercices de respiration et méditations</span></li><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Journal de bord personnel</span></li><li className="flex items-start gap-3"><CheckCircle className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" /><span className="text-base text-anthracite font-sans">Messages écrits (synchronisés plus tard)</span></li></ul></div></div></motion.div></div></section>
      <section className="py-12 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><div className="bg-gradient-to-br from-terracotta/5 via-beige/10 to-gold/5 border border-beige/30 rounded-2xl p-8"><h3 className="text-2xl font-serif text-anthracite mb-4">Comment ça marche ?</h3><p className="text-base text-muted-foreground font-sans leading-relaxed mb-6">L'application télécharge automatiquement vos données essentielles lorsque vous êtes connecté, pour qu'elles restent disponibles même hors ligne. Lorsque vous retrouvez une connexion, tout se synchronise automatiquement.</p><div className="bg-white rounded-xl p-6 border border-beige/30"><h4 className="text-lg font-serif text-anthracite mb-3">Conseils pour optimiser l'expérience offline</h4><ul className="space-y-2"><li className="flex items-start gap-3"><span className="text-terracotta mt-1">•</span><span className="text-sm text-anthracite font-sans">Téléchargez vos articles préférés avant un voyage</span></li><li className="flex items-start gap-3"><span className="text-terracotta mt-1">•</span><span className="text-sm text-anthracite font-sans">Activez la synchronisation automatique quand vous êtes en Wi-Fi</span></li><li className="flex items-start gap-3"><span className="text-terracotta mt-1">•</span><span className="text-sm text-anthracite font-sans">Consultez régulièrement votre Passeport Santé pour qu'il reste à jour</span></li></ul></div></div><div className="mt-8 text-center"><Link to="/help/telecharger-app" className="inline-flex items-center gap-2 px-8 py-4 bg-terracotta text-white rounded-full hover:bg-terracotta/90 transition-all duration-200 font-sans font-semibold shadow-lg hover:shadow-xl group">Télécharger l'application<ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" /></Link></div></motion.div></div></section>
      <section className="py-20 bg-gradient-to-b from-white to-beige/10"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-serif text-anthracite mb-6">Articles associés</h2><div className="grid md:grid-cols-2 gap-4"><Link to="/help/telecharger-app" className="p-6 bg-white hover:bg-beige/5 border border-beige/30 rounded-xl transition-all duration-200 group"><h3 className="text-lg font-serif text-anthracite group-hover:text-terracotta transition-colors mb-2">Comment télécharger l'application ?</h3><p className="text-sm text-muted-foreground font-sans">Installez M.O.N.A sur votre téléphone.</p></Link><Link to="/help/fonctionnalites-offline" className="p-6 bg-white hover:bg-beige/5 border border-beige/30 rounded-xl transition-all duration-200 group"><h3 className="text-lg font-serif text-anthracite group-hover:text-terracotta transition-colors mb-2">Quelles fonctionnalités offline ?</h3><p className="text-sm text-muted-foreground font-sans">Tout ce que vous pouvez faire sans connexion.</p></Link></div></div></section>
      <FooterSection />
    </div>
  );
}
